baseURL = "http://example.org/"
languageCode = "en-us"
title = "Telegram's Data Clustering"
theme = "hugonews"

[taxonomies]
    tag = "tags"
    category = "categories"
    site = "sites"
    authors = "author"